CREATE USER univuser IDENTIFIED BY password;

GRANT CREATE SESSION TO univuser;
GRANT ALL PRIVILEGES TO univuser;

ALTER USER univuser DEFAULT TABLESPACE USERS;

CREATE TABLE univuser.Courses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    teacher_id INT
);

INSERT INTO univuser.Courses (name, teacher_id) VALUES
('Math 101', 1);

INSERT INTO univuser.Courses (name, teacher_id) VALUES
('Physics 101', 2);
